name: Update M3U File

on:
  schedule:
    # Run every 30 minutes
    - cron: "*/30 * * * *"

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your desired Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      # Run the Python script
      - name: Run scraper
        run: python your_script_name.py

      # Commit and push changes if M3U file is updated
      - name: Commit and push M3U updates
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add channels.m3u channels_with_names.m3u
            git commit -m "Update M3U file"
            git push
          fi
